version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-package:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn pkg
      - store_artifacts:
          path: dist/enbase-win.exe
          destination: enbase-win.exe
      - store_artifacts:
          path: dist/enbase-linux
          destination: enbase-linux
workflows:
    build-and-package:
      jobs:
        - build-and-package